// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v3.0.6
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL__TMP__RTAMANAGERC_H_
#define _TAO_IDL__TMP__RTAMANAGERC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "acscommonC.h"
#include "acscomponentC.h"

#if TAO_MAJOR_VERSION != 3 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 6
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_root/root_ch.cpp:155


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace rtamanager
{
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_RTAMANAGER_DATAPROCESSOR__VAR_OUT_CH_)
#define _RTAMANAGER_DATAPROCESSOR__VAR_OUT_CH_

  class DataProcessor;
  using DataProcessor_ptr = DataProcessor*;
  using DataProcessor_var = TAO_Objref_Var_T<DataProcessor>;
  using DataProcessor_out = TAO_Objref_Out_T<DataProcessor>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  DataProcessor
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<DataProcessor>;
    // TAO_IDL - Generated from
    // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_type.cpp:296

    using _ptr_type = DataProcessor_ptr;
    using _var_type = DataProcessor_var;
    using _out_type = DataProcessor_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static DataProcessor_ptr _duplicate (DataProcessor_ptr obj);

    static void _tao_release (DataProcessor_ptr obj);

    static DataProcessor_ptr _narrow (::CORBA::Object_ptr obj);
    static DataProcessor_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DataProcessor_ptr _nil ();

    virtual void configure (
      const char * jsonStaticConfiguration);

    
    // TAO_IDL - Generated from
    // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    DataProcessor ();

    // Concrete non-local interface only.
    DataProcessor (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    DataProcessor (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~DataProcessor () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    DataProcessor (const DataProcessor &) = delete;
    DataProcessor (DataProcessor &&) = delete;
    DataProcessor &operator= (const DataProcessor &) = delete;
    DataProcessor &operator= (DataProcessor &&) = delete;
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_DataProcessor;
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_enum/enum_ch.cpp:39

  enum Commands
  {
    SHUTDOWN,
    CLEANED_SHUTDOWN,
    START,
    STOP,
    RESET,
    START_DATA,
    STOP_DATA,
    GET_STATUS
  };

  typedef Commands &Commands_out;
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_Commands;
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_RTAMANAGER_COMMANDER__VAR_OUT_CH_)
#define _RTAMANAGER_COMMANDER__VAR_OUT_CH_

  class Commander;
  using Commander_ptr = Commander*;
  using Commander_var = TAO_Objref_Var_T<Commander>;
  using Commander_out = TAO_Objref_Out_T<Commander>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  Commander
    : public virtual ::ACS::ACSComponent
  
  {
  public:
    friend class TAO::Narrow_Utils<Commander>;
    // TAO_IDL - Generated from
    // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_type.cpp:296

    using _ptr_type = Commander_ptr;
    using _var_type = Commander_var;
    using _out_type = Commander_out;

    static void _tao_any_destructor (void *);

    // The static operations.
    static Commander_ptr _duplicate (Commander_ptr obj);

    static void _tao_release (Commander_ptr obj);

    static Commander_ptr _narrow (::CORBA::Object_ptr obj);
    static Commander_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static Commander_ptr _nil ();

    virtual void configure (
      const char * jsonStaticConfiguration);

    virtual void sendCommand (
      ::rtamanager::Commands command,
      const char * destProcessorName);

    
    // TAO_IDL - Generated from
    // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Concrete interface only.
    Commander ();

    // Concrete non-local interface only.
    Commander (::IOP::IOR *ior, TAO_ORB_Core *orb_core);
    
    // Non-local interface only.
    Commander (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = nullptr,
        TAO_ORB_Core *orb_core = nullptr);

    virtual ~Commander () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    Commander (const Commander &) = delete;
    Commander (Commander &&) = delete;
    Commander &operator= (const Commander &) = delete;
    Commander &operator= (Commander &&) = delete;
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_typecode/typecode_decl.cpp:33

  extern  ::CORBA::TypeCode_ptr const _tc_Commander;


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module rtamanager
// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_RTAMANAGER_DATAPROCESSOR__ARG_TRAITS_)
#define _RTAMANAGER_DATAPROCESSOR__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::rtamanager::DataProcessor>
    : public Object_Arg_Traits_T<
        ::rtamanager::DataProcessor_ptr,
        ::rtamanager::DataProcessor_var,
        ::rtamanager::DataProcessor_out,
        TAO::Objref_Traits<rtamanager::DataProcessor>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:889

  

  template<>
  class Arg_Traits< ::rtamanager::Commands>
    : public
        Basic_Arg_Traits_T<
            ::rtamanager::Commands,
            TAO::Any_Insert_Policy_Stream
          >
  {
  };
  // TAO_IDL - Generated from
  // /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:142

  

#if !defined (_RTAMANAGER_COMMANDER__ARG_TRAITS_)
#define _RTAMANAGER_COMMANDER__ARG_TRAITS_

  template<>
  class  Arg_Traits< ::rtamanager::Commander>
    : public Object_Arg_Traits_T<
        ::rtamanager::Commander_ptr,
        ::rtamanager::Commander_var,
        ::rtamanager::Commander_out,
        TAO::Objref_Traits<rtamanager::Commander>,
        TAO::Any_Insert_Policy_Stream>
  {
  };

#endif /* end #if !defined */
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_RTAMANAGER_DATAPROCESSOR__TRAITS_)
#define _RTAMANAGER_DATAPROCESSOR__TRAITS_

  template<>
  struct  Objref_Traits< ::rtamanager::DataProcessor>
  {
    static ::rtamanager::DataProcessor_ptr duplicate (::rtamanager::DataProcessor_ptr p);
    static void release (::rtamanager::DataProcessor_ptr p);
    static ::rtamanager::DataProcessor_ptr nil ();
    static ::CORBA::Boolean marshal (const ::rtamanager::DataProcessor_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_RTAMANAGER_COMMANDER__TRAITS_)
#define _RTAMANAGER_COMMANDER__TRAITS_

  template<>
  struct  Objref_Traits< ::rtamanager::Commander>
  {
    static ::rtamanager::Commander_ptr duplicate (::rtamanager::Commander_ptr p);
    static void release (::rtamanager::Commander_ptr p);
    static ::rtamanager::Commander_ptr nil ();
    static ::CORBA::Boolean marshal (const ::rtamanager::Commander_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:40





#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace rtamanager
{
   void operator<<= ( ::CORBA::Any &, DataProcessor_ptr); // copying
   void operator<<= ( ::CORBA::Any &, DataProcessor_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DataProcessor_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, rtamanager::DataProcessor_ptr); // copying
 void operator<<= (::CORBA::Any &, rtamanager::DataProcessor_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, rtamanager::DataProcessor_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif
// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_enum/any_op_ch.cpp:31



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace rtamanager
{
  

   void operator<<= (::CORBA::Any &, ::rtamanager::Commands);
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, ::rtamanager::Commands &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL



 void operator<<= (::CORBA::Any &, rtamanager::Commands);
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, rtamanager::Commands &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/any_op_ch.cpp:40





#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace rtamanager
{
   void operator<<= ( ::CORBA::Any &, Commander_ptr); // copying
   void operator<<= ( ::CORBA::Any &, Commander_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Commander_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, rtamanager::Commander_ptr); // copying
 void operator<<= (::CORBA::Any &, rtamanager::Commander_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, rtamanager::Commander_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const rtamanager::DataProcessor_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, rtamanager::DataProcessor_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_enum/cdr_op_ch.cpp:33


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, rtamanager::Commands _tao_enumerator);
 ::CORBA::Boolean operator>> (TAO_InputCDR &strm, rtamanager::Commands &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL




// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_visitor_interface/cdr_op_ch.cpp:40



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const rtamanager::Commander_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, rtamanager::Commander_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /alma/ACS-2023AUG/TAO/ACE_wrappers/build/linux/TAO/TAO_IDL/be/be_codegen.cpp:1639

#if defined (__ACE_INLINE__)
#include "rtamanagerC.inl"
#endif /* defined INLINE */

#endif /* ifndef */

